contact_links:
  - name: Game crashing or scripts not running
    url: https://script-ware.com/discord
    about: Issues related to the exploit cannot be reported here
  - name: Windows/iOS/Ro-Ware problems
    url: https://script-ware.com/discord
    about: This is only for SWM
